// Code generated by lua-bindgen. DO NOT EDIT.

package serde

import (
	"github.com/speedata/go-lua"
)

const QUERY_HANDLE = "go/std/serde/query/Query*"

func QueryToLua(l *lua.State, query *Query) {
	l.PushUserData(query)
	lua.SetMetaTableNamed(l, QUERY_HANDLE)
}
func toQuery(l *lua.State, idx int) *Query {
	return lua.CheckUserData(l, idx, QUERY_HANDLE).(*Query)
}
func luaQueryFromRaw(l *lua.State) int {
	query := toQuery(l, 1)
	raw, _ := l.ToString(2)
	query.FromRaw(raw)
	return 0
}
func luaQuerySize(l *lua.State) {
	query := toQuery(l, 1)
	l.PushInteger(query.Size())
}
func luaQueryHas(l *lua.State) int {
	query := toQuery(l, 1)
	key, _ := l.ToString(2)
	l.PushBoolean(query.Has(key))
	return 1
}
func luaQueryGet(l *lua.State) int {
	query := toQuery(l, 1)
	key, _ := l.ToString(2)
	s := query.Get(key)
	if s == "" {
		l.PushNil()
	} else {
		l.PushString(s)
	}
	return 1
}
func luaQueryGetAll(l *lua.State) int {
	query := toQuery(l, 1)
	key, _ := l.ToString(2)
	items := query.GetAll(key)
	l.NewTable()
	for i, item := range items {
		l.PushInteger(i + 1)
		l.PushString(item)
		l.SetTable(-3)
	}
	return 1
}
func luaQuerySet(l *lua.State) int {
	query := toQuery(l, 1)
	key, _ := l.ToString(2)
	value, _ := l.ToString(3)
	query.Set(key, value)
	return 0
}
func luaQueryAppend(l *lua.State) int {
	query := toQuery(l, 1)
	key, _ := l.ToString(2)
	value, _ := l.ToString(3)
	query.Append(key, value)
	return 0
}
func luaQueryDelete(l *lua.State) int {
	query := toQuery(l, 1)
	key, _ := l.ToString(2)
	query.Delete(key)
	return 0
}
func luaQuerySort(l *lua.State) int {
	query := toQuery(l, 1)

	query.Sort()
	return 0
}
func luaQueryToString(l *lua.State) int {
	query := toQuery(l, 1)

	l.PushString(query.ToString())
	return 1
}
func luaQueryKeys(l *lua.State) int {
	query := toQuery(l, 1)

	items := query.Keys()
	l.NewTable()
	for i, item := range items {
		l.PushInteger(i + 1)
		l.PushString(item)
		l.SetTable(-3)
	}
	return 1
}
func luaQueryValues(l *lua.State) int {
	query := toQuery(l, 1)

	items := query.Values()
	l.NewTable()
	for i, item := range items {
		l.PushInteger(i + 1)
		l.PushString(item)
		l.SetTable(-3)
	}
	return 1
}
func luaQueryEntries(l *lua.State) int {
	query := toQuery(l, 1)

	items := query.Entries()
	l.NewTable()
	for i, entry := range items {
		l.PushInteger(i + 1)
		l.NewTable()
		l.PushInteger(1)
		l.PushString(entry[0])
		l.SetTable(-3)
		l.PushInteger(2)
		l.PushString(entry[1])
		l.SetTable(-3)
		l.SetTable(-3)
	}
	return 1
}

var queryMethods = map[string]lua.Function{
	"from_raw":  luaQueryFromRaw,
	"has":       luaQueryHas,
	"get":       luaQueryGet,
	"get_all":   luaQueryGetAll,
	"set":       luaQuerySet,
	"append":    luaQueryAppend,
	"delete":    luaQueryDelete,
	"sort":      luaQuerySort,
	"to_string": luaQueryToString,
	"keys":      luaQueryKeys,
	"values":    luaQueryValues,
	"entries":   luaQueryEntries,
}

var queryGetters = map[string]func(*lua.State){
	"size": luaQuerySize,
}
