// Code generated by lua-bindgen. DO NOT EDIT.

package serde

import (
	"github.com/ggallovalle/go-effectual"
	"github.com/speedata/go-lua"
	"strings"
	"text/template"
)

const QUERY_HANDLE = "go/std/serde/query/Query*"

func QueryToLua(l *lua.State, query *Query) {
	l.PushUserData(query)
	lua.SetMetaTableNamed(l, QUERY_HANDLE)
}
func toQuery(l *lua.State, idx int) *Query {
	return lua.CheckUserData(l, idx, QUERY_HANDLE).(*Query)
}
func luaQueryFromRaw(l *lua.State) int {
	query := toQuery(l, 1)
	raw, _ := l.ToString(2)
	query.FromRaw(raw)
	return 0
}
func luaQuerySize(l *lua.State) {
	query := toQuery(l, 1)
	l.PushInteger(query.Size())
}
func luaQueryHas(l *lua.State) int {
	query := toQuery(l, 1)
	key, _ := l.ToString(2)
	l.PushBoolean(query.Has(key))
	return 1
}
func luaQueryGet(l *lua.State) int {
	query := toQuery(l, 1)
	key, _ := l.ToString(2)
	s := query.Get(key)
	if s == "" {
		l.PushNil()
	} else {
		l.PushString(s)
	}
	return 1
}
func luaQueryGetAll(l *lua.State) int {
	query := toQuery(l, 1)
	key, _ := l.ToString(2)
	items := query.GetAll(key)
	l.NewTable()
	for i, item := range items {
		l.PushInteger(i + 1)
		l.PushString(item)
		l.SetTable(-3)
	}
	return 1
}
func luaQuerySet(l *lua.State) int {
	query := toQuery(l, 1)
	key, _ := l.ToString(2)
	value, _ := l.ToString(3)
	query.Set(key, value)
	return 0
}
func luaQueryAppend(l *lua.State) int {
	query := toQuery(l, 1)
	key, _ := l.ToString(2)
	value, _ := l.ToString(3)
	query.Append(key, value)
	return 0
}
func luaQueryDelete(l *lua.State) int {
	query := toQuery(l, 1)
	key, _ := l.ToString(2)
	query.Delete(key)
	return 0
}
func luaQuerySort(l *lua.State) int {
	query := toQuery(l, 1)

	query.Sort()
	return 0
}
func luaQueryToString(l *lua.State) int {
	query := toQuery(l, 1)

	l.PushString(query.ToString())
	return 1
}
func luaQueryKeys(l *lua.State) int {
	query := toQuery(l, 1)

	items := query.Keys()
	l.NewTable()
	for i, item := range items {
		l.PushInteger(i + 1)
		l.PushString(item)
		l.SetTable(-3)
	}
	return 1
}
func luaQueryValues(l *lua.State) int {
	query := toQuery(l, 1)

	items := query.Values()
	l.NewTable()
	for i, item := range items {
		l.PushInteger(i + 1)
		l.PushString(item)
		l.SetTable(-3)
	}
	return 1
}
func luaQueryEntries(l *lua.State) int {
	query := toQuery(l, 1)

	items := query.Entries()
	l.NewTable()
	for i, entry := range items {
		l.PushInteger(i + 1)
		l.NewTable()
		l.PushInteger(1)
		l.PushString(entry[0])
		l.SetTable(-3)
		l.PushInteger(2)
		l.PushString(entry[1])
		l.SetTable(-3)
		l.SetTable(-3)
	}
	return 1
}

var queryMethods = map[string]lua.Function{
	"from_raw":  luaQueryFromRaw,
	"has":       luaQueryHas,
	"get":       luaQueryGet,
	"get_all":   luaQueryGetAll,
	"set":       luaQuerySet,
	"append":    luaQueryAppend,
	"delete":    luaQueryDelete,
	"sort":      luaQuerySort,
	"to_string": luaQueryToString,
	"keys":      luaQueryKeys,
	"values":    luaQueryValues,
	"entries":   luaQueryEntries,
}

var queryGetters = map[string]func(*lua.State){
	"size": luaQuerySize,
}

var queryMetatable = []lua.RegistryFunction{
	{Name: "__tostring", Function: QueryToString},
	{Name: "__pairs", Function: QueryPairs},
	{Name: "from_raw", Function: luaQueryFromRaw},
	{Name: "has", Function: luaQueryHas},
	{Name: "get", Function: luaQueryGet},
	{Name: "get_all", Function: luaQueryGetAll},
	{Name: "set", Function: luaQuerySet},
	{Name: "append", Function: luaQueryAppend},
	{Name: "delete", Function: luaQueryDelete},
	{Name: "sort", Function: luaQuerySort},
	{Name: "to_string", Function: luaQueryToString},
	{Name: "keys", Function: luaQueryKeys},
	{Name: "values", Function: luaQueryValues},
	{Name: "entries", Function: luaQueryEntries},
	effectual.LuaMetaIndex(queryGetters, nil),
}

func queryLibrary() []lua.RegistryFunction {
	return []lua.RegistryFunction{
		{Name: "new", Function: queryNew},
		{Name: "deserialize", Function: queryDeserialize},
		{Name: "serialize", Function: querySerialize},
	}
}

type ModQuery struct {
	name string
}

func (lib *ModQuery) Name() string {
	return lib.name
}

func (lib *ModQuery) Annotations() string {
	data := map[string]string{
		"module": lib.name,
		"Query":  lib.name + ".Query",
	}
	var buf strings.Builder
	if err := QueryAnnotationsTmpl.Execute(&buf, data); err != nil {
		return ""
	}
	return buf.String()
}

func (lib *ModQuery) Open(l *lua.State) int {
	lua.NewLibrary(l, queryLibrary())

	lua.NewMetaTable(l, QUERY_HANDLE)
	l.PushValue(-1)
	l.SetField(-2, "__index")
	lua.SetFunctions(l, queryMetatable, 0)
	l.Pop(1)

	return 1
}

func (lib *ModQuery) OpenLib(l *lua.State) {
	lua.Require(l, lib.name, lib.Open, false)
	l.Pop(1)
}

func (lib *ModQuery) Require(l *lua.State) {
	l.Global("require")
	l.PushString(lib.Name())
	l.Call(1, 1)
}

func MakeModQuery() effectual.LuaModDefinition {
	return &ModQuery{name: "std.serde.query"}
}

var QueryAnnotationsTmpl = template.Must(template.New("Query").Parse(`---@meta {{.module}}

---@class (exact) {{.Query}} : userdata
local Query = {}

---@param raw string
function Query:from_raw(raw) end

---@param 
---@return integer
function Query:size() end

---@param key string
---@return boolean
function Query:has(key) end

---@param key string
---@return string|nil
function Query:get(key) end

---@param key string
---@return string[]
function Query:get_all(key) end

---@param key string
value string
function Query:set(key, value) end

---@param key string
value string
function Query:append(key, value) end

---@param key string
function Query:delete(key) end

---@param 
function Query:sort() end

---@param 
---@return string
function Query:to_string() end

---@param 
---@return string[]
function Query:keys() end

---@param 
---@return string[]
function Query:values() end

---@param 
---@return {[1]: string, [2]: string}[]
function Query:entries() end

local q = {}

---@param 
---@return {{.Query}}
function q.new() end

---@param raw string
---@return {{.Query}}
function q.deserialize(raw) end

---@param q {{.Query}}
---@return string
function q.serialize(q) end

return q
`))

func queryNew(l *lua.State) int {
	q := NewQuery()
	QueryToLua(l, q)
	return 1
}
func queryDeserialize(l *lua.State) int {
	raw, _ := l.ToString(1)
	q := NewQuery()
	if raw != "" {
		q.FromRaw(raw)
	}
	QueryToLua(l, q)
	return 1
}
func querySerialize(l *lua.State) int {
	q := toQuery(l, 1)
	l.PushString(q.ToString())
	return 1
}
