package luagen

import (
	"fmt"
	"sort"
	"strings"
)

func Generate(info *TypeInfo, cfg *GenConfig) string {
	handlePath := strings.ReplaceAll(cfg.Module, ".", "/")
	info.Handle = "go/" + handlePath + "/" + info.Name + "*"

	var b strings.Builder

	b.WriteString("// Code generated by lua-bindgen. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", info.Package))

	imports := collectImports(info, cfg)
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString(fmt.Sprintf("\t%s\n", imp))
		}
		b.WriteString(")\n\n")
	}

	b.WriteString(fmt.Sprintf("const %s_HANDLE = \"%s\"\n\n", strings.ToUpper(info.Name), info.Handle))

	b.WriteString(genToLua(info))
	b.WriteString("\n")
	b.WriteString(genFromLua(info))
	b.WriteString("\n")

	// Field getters
	for _, f := range info.Fields {
		if cfg.IsFieldSkipped(f.Name) || f.IsSkipped {
			continue
		}
		b.WriteString(genFieldGetter(info, f))
		b.WriteString("\n")
	}

	// Method getters and wrappers
	for _, m := range info.Methods {
		if m.IsSkipped {
			continue
		}
		if m.IsGetter {
			b.WriteString(genGetter(info, m))
			b.WriteString("\n")
		} else {
			b.WriteString(genMethod(info, m))
			b.WriteString("\n")
		}
	}

	b.WriteString(genMethodsMap(info))
	b.WriteString("\n")
	b.WriteString(genGettersMap(info))
	b.WriteString("\n")
	if len(info.Metamethods) > 0 {
		b.WriteString(genMetatable(info))
		b.WriteString("\n")
	}
	b.WriteString(genLibrary(info))
	b.WriteString("\n")

	return b.String()
}

func collectImports(info *TypeInfo, cfg *GenConfig) []string {
	imports := make(map[string]string)
	imports["\"github.com/speedata/go-lua\""] = ""

	if len(info.Metamethods) > 0 {
		imports["\"github.com/ggallovalle/go-effectual\""] = ""
	}

	for _, m := range info.Methods {
		if m.IsSkipped {
			continue
		}
		if m.PtrType != "" && m.PtrType != info.Name {
			if alias, ok := cfg.Imports[m.PtrType]; ok {
				imports[fmt.Sprintf("%s \"%s\"", alias, alias)] = ""
			}
		}
	}

	// Check field types for external types
	for _, f := range info.Fields {
		if cfg.IsFieldSkipped(f.Name) {
			continue
		}
		ft := strings.TrimPrefix(f.Type, "*")
		if strings.Contains(ft, ".") {
			parts := strings.SplitN(ft, ".", 2)
			if alias, ok := cfg.Imports[parts[0]]; ok {
				imports[fmt.Sprintf("%s \"%s\"", parts[0], alias)] = ""
			}
		}
	}

	for alias, path := range cfg.Imports {
		if path == "" {
			continue
		}
		lastSeg := path
		if idx := strings.LastIndex(path, "/"); idx >= 0 {
			lastSeg = path[idx+1:]
		}
		if lastSeg == info.Package {
			continue
		}
		if alias == "" {
			imports[fmt.Sprintf("\"%s\"", path)] = ""
		} else {
			imports[fmt.Sprintf("%s \"%s\"", alias, path)] = ""
		}
	}

	result := make([]string, 0, len(imports))
	for imp := range imports {
		result = append(result, imp)
	}
	sort.Strings(result)
	return result
}

func genToLua(info *TypeInfo) string {
	vn := info.VarName()
	return fmt.Sprintf(`func %sToLua(l *lua.State, %s *%s) {
	l.PushUserData(%s)
	lua.SetMetaTableNamed(l, %s_HANDLE)
}`, info.Name, vn, info.Name, vn, strings.ToUpper(info.Name))
}

func genFromLua(info *TypeInfo) string {
	return fmt.Sprintf(`func to%s(l *lua.State, idx int) *%s {
	return lua.CheckUserData(l, idx, %s_HANDLE).(*%s)
}`, info.Name, info.Name, strings.ToUpper(info.Name), info.Name)
}

func genFieldGetter(info *TypeInfo, f FieldInfo) string {
	vn := info.VarName()
	body := genFieldGetterBody(info, f)

	return fmt.Sprintf(`func lua%s%s(l *lua.State) {
	%s := to%s(l, 1)
%s
}`, info.Name, f.Name, vn, info.Name, indent(body, 1))
}

func genFieldGetterBody(info *TypeInfo, f FieldInfo) string {
	vn := info.VarName()
	access := fmt.Sprintf("%s.%s", vn, f.Name)

	switch f.Type {
	case "bool":
		return fmt.Sprintf("l.PushBoolean(%s)", access)
	case "int", "int64":
		return fmt.Sprintf("l.PushInteger(%s)", access)
	case "string":
		return fmt.Sprintf(`if %s == "" {
		l.PushNil()
	} else {
		l.PushString(%s)
	}`, access, access)
	case "*int":
		return fmt.Sprintf(`if %s == nil {
		l.PushNil()
	} else {
		l.PushInteger(*%s)
	}`, access, access)
	case "*string":
		return fmt.Sprintf(`if %s == nil {
		l.PushNil()
	} else {
		l.PushString(*%s)
	}`, access, access)
	case "*float64":
		return fmt.Sprintf(`if %s == nil {
		l.PushNil()
	} else {
		l.PushNumber(*%s)
	}`, access, access)
	default:
		// Check if it's a pointer to a known type
		if strings.HasPrefix(f.Type, "*") {
			ptrType := f.Type[1:]
			// Check if it has a package qualifier
			if strings.Contains(ptrType, ".") {
				parts := strings.SplitN(ptrType, ".", 2)
				return fmt.Sprintf("%s.%sToLua(l, %s)", parts[0], parts[1], access)
			}
			return fmt.Sprintf("%sToLua(l, %s)", ptrType, access)
		}
		// Non-pointer type
		if strings.Contains(f.Type, ".") {
			parts := strings.SplitN(f.Type, ".", 2)
			return fmt.Sprintf("%s.%sToLua(l, &%s)", parts[0], parts[1], access)
		}
		return fmt.Sprintf("%sToLua(l, &%s)", f.Type, access)
	}
}

func genGetter(info *TypeInfo, m MethodInfo) string {
	vn := info.VarName()
	body := genGetterBody(info, m)

	return fmt.Sprintf(`func lua%s%s(l *lua.State) {
	%s := to%s(l, 1)
%s
}`, info.Name, m.Name, vn, info.Name, indent(body, 1))
}

func genGetterBody(info *TypeInfo, m MethodInfo) string {
	vn := info.VarName()
	call := fmt.Sprintf("%s.%s()", vn, m.Name)

	switch m.ReturnKind {
	case ReturnBool:
		return fmt.Sprintf("l.PushBoolean(%s)", call)
	case ReturnInt, ReturnInt64:
		return fmt.Sprintf("l.PushInteger(%s)", call)
	case ReturnString:
		if m.IsNilMap {
			return fmt.Sprintf(`s := %s
	if s == "" {
		l.PushNil()
	} else {
		l.PushString(s)
	}`, call)
		}
		return fmt.Sprintf("l.PushString(%s)", call)
	case ReturnStringSlice:
		return fmt.Sprintf(`items := %s
	l.NewTable()
	for i, item := range items {
		l.PushInteger(i + 1)
		l.PushString(item)
		l.SetTable(-3)
	}`, call)
	case ReturnPointer:
		return fmt.Sprintf(`result := %s
	if result == nil {
		l.PushNil()
	} else {
		%sToLua(l, result)
	}`, call, m.PtrType)
	case ReturnPointerSlice:
		return fmt.Sprintf(`items := %s
	l.NewTable()
	for i, item := range items {
		l.PushInteger(i + 1)
		%sToLua(l, item)
		l.SetTable(-3)
	}`, call, m.PtrType)
	case ReturnTupleSlice:
		return fmt.Sprintf(`items := %s
	l.NewTable()
	for i, entry := range items {
		l.PushInteger(i + 1)
		l.NewTable()
		l.PushInteger(1)
		l.PushString(entry[0])
		l.SetTable(-3)
		l.PushInteger(2)
		l.PushString(entry[1])
		l.SetTable(-3)
		l.SetTable(-3)
	}`, call)
	default:
		return fmt.Sprintf("// TODO: manual impl getter for %s returning %s", m.Name, m.ReturnType)
	}
}

func genMethod(info *TypeInfo, m MethodInfo) string {
	vn := info.VarName()

	if m.ReturnKind == ReturnComplex {
		return fmt.Sprintf(`func lua%s%s(l *lua.State) int {
	// TODO: manual impl for %s returning %s
	return 0
}`, info.Name, m.Name, m.Name, m.ReturnType)
	}

	paramExtract := genParamExtract(m, vn)
	call := genMethodCall(info, m, vn)
	retCount := genReturnCount(m)

	return fmt.Sprintf(`func lua%s%s(l *lua.State) int {
	%s := to%s(l, 1)
%s
%s
}`, info.Name, m.Name, vn, info.Name, paramExtract, indent(call+"\n"+retCount, 1))
}

func genParamExtract(m MethodInfo, receiverName string) string {
	var b strings.Builder
	for i, p := range m.Params {
		luaIdx := i + 2
		paramName := p.Name
		if paramName == receiverName {
			paramName = "arg" + fmt.Sprintf("%d", i)
		}
		switch p.Type {
		case "string":
			b.WriteString(fmt.Sprintf("%s, _ := l.ToString(%d)\n", paramName, luaIdx))
		case "int":
			b.WriteString(fmt.Sprintf("%s, _ := l.ToInteger(%d)\n", paramName, luaIdx))
		case "int64":
			b.WriteString(fmt.Sprintf("%s := int64(0)\n", paramName))
			b.WriteString(fmt.Sprintf("if v, _ := l.ToInteger(%d); v != 0 || true {\n", luaIdx))
			b.WriteString(fmt.Sprintf("\t%s = int64(v)\n}\n", paramName))
		case "bool":
			b.WriteString(fmt.Sprintf("%s := l.ToBoolean(%d)\n", paramName, luaIdx))
		case "float64":
			b.WriteString(fmt.Sprintf("%s, _ := l.ToNumber(%d)\n", paramName, luaIdx))
		default:
			b.WriteString(fmt.Sprintf("// TODO: extract param %s of type %s\n", paramName, p.Type))
		}
	}
	return strings.TrimRight(b.String(), "\n")
}

func genMethodCall(info *TypeInfo, m MethodInfo, receiverName string) string {
	vn := info.VarName()
	args := make([]string, len(m.Params))
	for i, p := range m.Params {
		paramName := p.Name
		if paramName == receiverName {
			paramName = "arg" + fmt.Sprintf("%d", i)
		}
		args[i] = paramName
	}
	call := fmt.Sprintf("%s.%s(%s)", vn, m.Name, strings.Join(args, ", "))

	if m.ReturnKind == ReturnVoid {
		return call
	}

	switch m.ReturnKind {
	case ReturnBool:
		return fmt.Sprintf("l.PushBoolean(%s)", call)
	case ReturnInt, ReturnInt64:
		return fmt.Sprintf("l.PushInteger(%s)", call)
	case ReturnString:
		if m.IsNilMap {
			return fmt.Sprintf(`s := %s
	if s == "" {
		l.PushNil()
	} else {
		l.PushString(s)
	}`, call)
		}
		return fmt.Sprintf("l.PushString(%s)", call)
	case ReturnStringSlice:
		return fmt.Sprintf(`items := %s
	l.NewTable()
	for i, item := range items {
		l.PushInteger(i + 1)
		l.PushString(item)
		l.SetTable(-3)
	}`, call)
	case ReturnPointer:
		return fmt.Sprintf(`result := %s
	if result == nil {
		l.PushNil()
	} else {
		%sToLua(l, result)
	}`, call, m.PtrType)
	case ReturnPointerSlice:
		return fmt.Sprintf(`items := %s
	l.NewTable()
	for i, item := range items {
		l.PushInteger(i + 1)
		%sToLua(l, item)
		l.SetTable(-3)
	}`, call, m.PtrType)
	case ReturnTupleSlice:
		return fmt.Sprintf(`items := %s
	l.NewTable()
	for i, entry := range items {
		l.PushInteger(i + 1)
		l.NewTable()
		l.PushInteger(1)
		l.PushString(entry[0])
		l.SetTable(-3)
		l.PushInteger(2)
		l.PushString(entry[1])
		l.SetTable(-3)
		l.SetTable(-3)
	}`, call)
	default:
		return fmt.Sprintf("// TODO: manual impl for %s returning %s", m.Name, m.ReturnType)
	}
}

func genReturnCount(m MethodInfo) string {
	switch m.ReturnKind {
	case ReturnVoid:
		return "return 0"
	case ReturnComplex:
		return "return 0"
	default:
		return "return 1"
	}
}

func genMethodsMap(info *TypeInfo) string {
	vn := info.VarName()
	var b strings.Builder
	b.WriteString(fmt.Sprintf("var %sMethods = map[string]lua.Function{\n", vn))

	for _, m := range info.Methods {
		if m.IsSkipped || m.IsGetter {
			continue
		}
		if isMetamethod(info, m.Name) {
			continue
		}
		b.WriteString(fmt.Sprintf("\t\"%s\": lua%s%s,\n", ToSnake(m.Name), info.Name, m.Name))
	}

	b.WriteString("}\n")
	return b.String()
}

func isMetamethod(info *TypeInfo, methodName string) bool {
	for _, mm := range info.Metamethods {
		if mm.Name == methodName {
			return true
		}
	}
	return false
}

func genGettersMap(info *TypeInfo) string {
	vn := info.VarName()
	var b strings.Builder
	b.WriteString(fmt.Sprintf("var %sGetters = map[string]func(*lua.State){\n", vn))

	// Field getters
	for _, f := range info.Fields {
		if f.IsSkipped {
			continue
		}
		b.WriteString(fmt.Sprintf("\t\"%s\": lua%s%s,\n", ToSnake(f.Name), info.Name, f.Name))
	}

	// Method getters
	for _, m := range info.Methods {
		if m.IsSkipped || !m.IsGetter {
			continue
		}
		b.WriteString(fmt.Sprintf("\t\"%s\": lua%s%s,\n", ToSnake(m.Name), info.Name, m.Name))
	}

	b.WriteString("}\n")
	return b.String()
}

func genMetatable(info *TypeInfo) string {
	vn := info.VarName()
	stringMethod := "String()"
	hasString := false
	for _, m := range info.Methods {
		if m.Name == "String" {
			hasString = true
			break
		}
	}
	if !hasString {
		for _, m := range info.Methods {
			if m.Name == "ToString" {
				stringMethod = "ToString()"
				break
			}
		}
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("var %sMetatable = []lua.RegistryFunction{\n", vn))
	b.WriteString("\t{Name: \"__tostring\", Function: func(l *lua.State) int {\n")
	b.WriteString(fmt.Sprintf("\t\t%s := to%s(l, 1)\n", vn, info.Name))
	b.WriteString(fmt.Sprintf("\t\tl.PushString(%s.%s)\n", vn, stringMethod))
	b.WriteString("\t\treturn 1\n")
	b.WriteString("\t}},\n")

	// Metamethods
	for _, mm := range info.Metamethods {
		b.WriteString(fmt.Sprintf("\t{Name: \"__%s\", Function: lua%s%s},\n", mm.LuaName, info.Name, mm.Name))
	}

	b.WriteString(fmt.Sprintf("\teffectual.LuaMetaIndex(%sGetters, %sMethods),\n", vn, vn))
	b.WriteString("}\n")
	return b.String()
}

func genLibrary(info *TypeInfo) string {
	vn := info.VarName()
	if len(info.ModuleFuncs) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("func %sLibrary() []lua.RegistryFunction {\n", vn))
	b.WriteString("\treturn []lua.RegistryFunction{\n")
	for _, mf := range info.ModuleFuncs {
		b.WriteString(fmt.Sprintf("\t\t{Name: \"%s\", Function: %s},\n", mf.LuaName, mf.Name))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

func indent(s string, level int) string {
	lines := strings.Split(s, "\n")
	prefix := strings.Repeat("\t", level)
	for i, line := range lines {
		if line != "" {
			lines[i] = prefix + line
		}
	}
	return strings.Join(lines, "\n")
}
