// Code generated by lua-bindgen. DO NOT EDIT.

package std

import (
	"github.com/speedata/go-lua"
)

const PATH_HANDLE = "go/std/path/Path*"

func PathToLua(l *lua.State, path *Path) {
	l.PushUserData(path)
	lua.SetMetaTableNamed(l, PATH_HANDLE)
}
func toPath(l *lua.State, idx int) *Path {
	return lua.CheckUserData(l, idx, PATH_HANDLE).(*Path)
}
func luaPathraw(l *lua.State) {
	path := toPath(l, 1)
	if path.raw == "" {
		l.PushNil()
	} else {
		l.PushString(path.raw)
	}
}
func luaPathsep(l *lua.State) {
	path := toPath(l, 1)
	if path.sep == "" {
		l.PushNil()
	} else {
		l.PushString(path.sep)
	}
}
func luaPathString(l *lua.State) {
	path := toPath(l, 1)
	l.PushString(path.String())
}
func luaPathPush(l *lua.State) int {
	path := toPath(l, 1)
	arg0, _ := l.ToString(2)
	path.Push(arg0)
	return 0
}
func luaPathPop(l *lua.State) int {
	path := toPath(l, 1)

	l.PushBoolean(path.Pop())
	return 1
}
func luaPathJoin(l *lua.State) int {
	path := toPath(l, 1)
	arg0, _ := l.ToString(2)
	result := path.Join(arg0)
	if result == nil {
		l.PushNil()
	} else {
		PathToLua(l, result)
	}
	return 1
}
func luaPathWithExtension(l *lua.State) int {
	path := toPath(l, 1)
	ext, _ := l.ToString(2)
	result := path.WithExtension(ext)
	if result == nil {
		l.PushNil()
	} else {
		PathToLua(l, result)
	}
	return 1
}
func luaPathWithFileName(l *lua.State) int {
	path := toPath(l, 1)
	name, _ := l.ToString(2)
	result := path.WithFileName(name)
	if result == nil {
		l.PushNil()
	} else {
		PathToLua(l, result)
	}
	return 1
}
func luaPathComponents(l *lua.State) {
	path := toPath(l, 1)
	items := path.Components()
	l.NewTable()
	for i, item := range items {
		l.PushInteger(i + 1)
		l.PushString(item)
		l.SetTable(-3)
	}
}
func luaPathAncestors(l *lua.State) {
	path := toPath(l, 1)
	items := path.Ancestors()
	l.NewTable()
	for i, item := range items {
		l.PushInteger(i + 1)
		PathToLua(l, item)
		l.SetTable(-3)
	}
}
func luaPathParent(l *lua.State) {
	path := toPath(l, 1)
	result := path.Parent()
	if result == nil {
		l.PushNil()
	} else {
		PathToLua(l, result)
	}
}
func luaPathFileName(l *lua.State) {
	path := toPath(l, 1)
	s := path.FileName()
	if s == "" {
		l.PushNil()
	} else {
		l.PushString(s)
	}
}
func luaPathExtension(l *lua.State) {
	path := toPath(l, 1)
	s := path.Extension()
	if s == "" {
		l.PushNil()
	} else {
		l.PushString(s)
	}
}
func luaPathFileStem(l *lua.State) {
	path := toPath(l, 1)
	s := path.FileStem()
	if s == "" {
		l.PushNil()
	} else {
		l.PushString(s)
	}
}
func luaPathHasRoot(l *lua.State) {
	path := toPath(l, 1)
	l.PushBoolean(path.HasRoot())
}
func luaPathIsAbsolute(l *lua.State) {
	path := toPath(l, 1)
	l.PushBoolean(path.IsAbsolute())
}
func luaPathIsRelative(l *lua.State) {
	path := toPath(l, 1)
	l.PushBoolean(path.IsRelative())
}

var pathMethods = map[string]lua.Function{
	"push":           luaPathPush,
	"pop":            luaPathPop,
	"join":           luaPathJoin,
	"with_extension": luaPathWithExtension,
	"with_file_name": luaPathWithFileName,
}

var pathGetters = map[string]func(*lua.State){
	"raw":         luaPathraw,
	"sep":         luaPathsep,
	"string":      luaPathString,
	"components":  luaPathComponents,
	"ancestors":   luaPathAncestors,
	"parent":      luaPathParent,
	"file_name":   luaPathFileName,
	"extension":   luaPathExtension,
	"file_stem":   luaPathFileStem,
	"has_root":    luaPathHasRoot,
	"is_absolute": luaPathIsAbsolute,
	"is_relative": luaPathIsRelative,
}
