// Code generated by lua-bindgen. DO NOT EDIT.

package std

import (
	"github.com/ggallovalle/go-effectual"
	serde "github.com/ggallovalle/go-effectual/std/serde"
	"github.com/speedata/go-lua"
)

const URL_HANDLE = "go/std/url/Url*"

func UrlToLua(l *lua.State, url *Url) {
	l.PushUserData(url)
	lua.SetMetaTableNamed(l, URL_HANDLE)
}
func toUrl(l *lua.State, idx int) *Url {
	return lua.CheckUserData(l, idx, URL_HANDLE).(*Url)
}
func luaUrlscheme(l *lua.State) {
	url := toUrl(l, 1)
	if url.scheme == "" {
		l.PushNil()
	} else {
		l.PushString(url.scheme)
	}
}
func luaUrlhost(l *lua.State) {
	url := toUrl(l, 1)
	if url.host == "" {
		l.PushNil()
	} else {
		l.PushString(url.host)
	}
}
func luaUrlport(l *lua.State) {
	url := toUrl(l, 1)
	if url.port == nil {
		l.PushNil()
	} else {
		l.PushInteger(*url.port)
	}
}
func luaUrlusername(l *lua.State) {
	url := toUrl(l, 1)
	if url.username == nil {
		l.PushNil()
	} else {
		l.PushString(*url.username)
	}
}
func luaUrlpassword(l *lua.State) {
	url := toUrl(l, 1)
	if url.password == nil {
		l.PushNil()
	} else {
		l.PushString(*url.password)
	}
}
func luaUrlpath(l *lua.State) {
	url := toUrl(l, 1)
	PathToLua(l, url.path)
}
func luaUrlquery(l *lua.State) {
	url := toUrl(l, 1)
	serde.QueryToLua(l, url.query)
}
func luaUrlfragment(l *lua.State) {
	url := toUrl(l, 1)
	if url.fragment == nil {
		l.PushNil()
	} else {
		l.PushString(*url.fragment)
	}
}
func luaUrlString(l *lua.State) {
	url := toUrl(l, 1)
	l.PushString(url.String())
}
func luaUrlAddQuery(l *lua.State) int {
	url := toUrl(l, 1)
	key, _ := l.ToString(2)
	value, _ := l.ToString(3)
	url.AddQuery(key, value)
	return 0
}
func luaUrlRemoveQuery(l *lua.State) int {
	url := toUrl(l, 1)
	key, _ := l.ToString(2)
	url.RemoveQuery(key)
	return 0
}
func luaUrlDiv(l *lua.State) int {
	url := toUrl(l, 1)
	path, _ := l.ToString(2)
	result := url.Div(path)
	if result == nil {
		l.PushNil()
	} else {
		UrlToLua(l, result)
	}
	return 1
}

var urlMethods = map[string]lua.Function{
	"add_query":    luaUrlAddQuery,
	"remove_query": luaUrlRemoveQuery,
}

var urlGetters = map[string]func(*lua.State){
	"scheme":   luaUrlscheme,
	"host":     luaUrlhost,
	"port":     luaUrlport,
	"username": luaUrlusername,
	"password": luaUrlpassword,
	"path":     luaUrlpath,
	"query":    luaUrlquery,
	"fragment": luaUrlfragment,
	"string":   luaUrlString,
}

var urlMetatable = []lua.RegistryFunction{
	{Name: "__tostring", Function: func(l *lua.State) int {
		url := toUrl(l, 1)
		l.PushString(url.String())
		return 1
	}},
	{Name: "__div", Function: luaUrlDiv},
	effectual.LuaMetaIndex(urlGetters, urlMethods),
}

func urlLibrary() []lua.RegistryFunction {
	return []lua.RegistryFunction{
		{Name: "new", Function: urlNew},
		{Name: "deserialize", Function: urlDeserialize},
		{Name: "serialize", Function: urlSerialize},
	}
}
